### ISSUE TITLE
[Product] Add a new product

### ISSUE THREAD

**Issue by Vadorequest** [UnlyEd/next-right-now-admin#11]
# Goals

Add a new product

# Roadmap 
- [x] with localised title
- [ ] with product image
- [x] must belong to a customer
- [ ] with localised RichText field (description)

# Pre-requisites
- #10 

# Technical specs
https://marmelab.com/react-admin/CreateEdit.html

Maybe https://github.com/Weakky/ra-data-opencrud/pull/14 will be helpful
